# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "metalmetrics-rs"
version = "0.0.1"
description = "Metal metrics in Rust"
readme = "README.md"
homepage = "https://github.com/craftslab/metalmetrics-rs"
repository = "https://github.com/craftslab/metalmetrics-rs"
license = "MIT"
authors = ["Jia Jia <angersax@sina.com>"]
categories = ["metrics", "network-programming"]
keywords = ["metal", "metrics", "rust"]
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
clap = "3.0.0-beta.4"
lettre = "0.10.0-rc.3"
